#! /bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1

pkill sxhkd
pgrep -x sxhkd >/dev/null || sxhkd &

monitor_count=$(xrandr --query | grep " connected " | wc -l)

if [ $monitor_count == 1 ]; then
	bspc monitor -d I II III IV V VI VII VIII IX X
elif [ $monitor_count == 2 ]; then
	bspc monitor HDMI-0 -n principal -d I II III IV V
	bspc monitor HDMI-1 -n secondary -d VI VII VIII IX X
	bspc monitor HDMI-0 -s HDMI-1
fi

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config border_width 3
bspc config focused_border_color \#C5C8C6
bspc config window_gap 5

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Zomodoro state=floating border=off
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Custom initialize
setxkbmap -layout us -variant altgr-intl # change keyboard layout
# Random wallpaper
# feh --randomize --bg-fill "${HOME}/.dotfiles/wallpapers/" &
feh --bg-fill "${HOME}/.dotfiles/wallpapers/wallpaper19.jpg" &

pkill dunst
dusnt &

pkill polybar
"${HOME}/.config/polybar/./launch.sh" &

pkill nm-applet
nm-applet &

pkill picom
picom &

pkill udiskie
udiskie -t &

# fix X cursor on no focused windows
xsetroot -cursor_name left_ptr &

# for applications which need privileges
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
