#! /bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1

pkill sxhkd
pgrep -x sxhkd >/dev/null || sxhkd &

monitor_count=$(xrandr --query | grep " connected " | wc -l)

if [ $monitor_count == 1 ]; then
	bspc monitor -d I II III IV V VI VII
elif [ $monitor_count == 2 ]; then
	bspc monitor HDMI-0 -n principal -d I II III IV
	bspc monitor HDMI-1 -n secondary -d V VI VII
	bspc monitor HDMI-0 -s HDMI-1
fi

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config border_width 1
bspc config window_gap 6

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Custom initialize
setxkbmap -layout us -variant altgr-intl # change keyboard layout
feh --bg-fill /home/zero/.dotfiles/wallpapers/wallpaper1.jpg &
/home/zero/.config/polybar/./launch.sh &
# /usr/bin/./eww open bar
nm-applet &
picom &
udiskie -t &
